[workspace]
members = [
  # tests and example code
  "examples",
  # the main library and tests
  "rustls",
]
exclude = ["admin/rustfmt"]
resolver = "2"

[patch.crates-io]
webpki = { git = "https://github.com/rustls/webpki", package = "rustls-webpki" }
